# Config file for automatic testing at travis-ci.org

sudo: required

services:
  - docker

language: python
python: 3.5
env:
    - TOX_ENV=py27
    - TOX_ENV=py34
    - TOX_ENV=py35

script:
    - tox -e $TOX_ENV
    - sh tests/test_docker.sh

install:
    - pip install tox

notifications:
  email:
    on_success: change
    on_failure: always
