# Config file for automatic testing at travis-ci.org

sudo: required

services:
  - docker

language: python

python: 3.5

env:
    - TOX_ENV=py27
    - TOX_ENV=py34
    - TOX_ENV=py35

before_install:
  - sudo apt-get update
  - sudo apt-get install -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" docker-engine=1.10.1-0~trusty
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.6.0/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
    - tox -e $TOX_ENV
    - sh tests/test_docker.sh

install:
    - pip install tox

notifications:
  email:
    on_success: change
    on_failure: always
