language: python
sudo: false
before_install:
  - time pip install pep8

install:
- pip install -r requirements.txt

script:
  - pep8 --ignore E201,E202 --max-line-length=120 --exclude='migrations' .
  - make test

notifications:
  email:
    on_success: change
    on_failure: always
